publisher:
  name: Moon Boi Studios 
  address: ' London, United Kingdom'
  website: http://moonboi.io/
  email: ems@moonboi.io
  media:
    - purpose: icon
      uri: "C:\Users\asad\Downloads\drive-download-20230818T171807Z-001\Icon.jpg"
app:
  name: Moon Boi Universe (Alpha)
  address: ''
  android_package: com.MoonBoiStudios.MoonBoiUniverse
  urls:
    license_url: <<URL_OF_APP_LICENSE_OR_TERMS_OF_SERVICE>>
    copyright_url: <<URL_OF_COPYRIGHT_DETAILS_FOR_APP>>
    privacy_policy_url: <<URL_OF_APP_PRIVACY_POLICY>>
    website: <<URL_OF_APP_WEBSITE>>
  media:
    - purpose: icon
      uri: "C:\Users\asad\Downloads\drive-download-20230818T171807Z-001\Icon.jpg"
release:
  address: ''
  media:
    - purpose: icon
      uri: "C:\Users\asad\Downloads\drive-download-20230818T171807Z-001\Icon.jpg"
    - purpose: screenshot
      uri: "C:\Users\asad\Downloads\drive-download-20230818T171807Z-001\Screenshot (8 Aug 2023 7_15_46 pm).png"
  files:
    - purpose: install
      uri: "C:\Users\asad\Downloads\drive-download-20230818T171807Z-001\MBU.apk"
  catalog:
    en-US:
      name: Moon Boi Universe (Alpha)
      short_description: Cyber Fantasy RPG
      long_description: Unleash Fun in Moon Boi Universe! Engage in alien battles, climb leaderboards, and dive into the new retro arcade using BONK tokens. Experience an interstellar journey packed with excitement, challenges, and endless enjoyment! 
      new_in_version: BONK BARKADE! Interact with BONK’s custom retro arcade, unlock, upgrade and have fun! 
      saga_features: <<ANY_FEATURES_ONLY_AVAILBLE_WHEN_RUNNING_ON_SAGA>>
solana_mobile_dapp_publisher_portal:
  google_store_package: <<ANDROID_PACKAGE_NAME_OF_GOOGLE_PLAY_STORE_VERSION_IF_DIFFERENT>>
  testing_instructions: <<TESTING_INSTRUCTIONS>>
